"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from glob import glob
from setuptools import setup

APP = ['TimeStamper.py']
DATA_FILES = ["time_stamper_class.py", ("ts_images", glob("ts_images/*.*")), \
    ("ts_macros", glob("ts_macros/*.*")), ("ts_template", glob("ts_template/*.*")), \
    ("ts_timer", glob("ts_timer/*.*"))]
OPTIONS = {"includes": ["tkmacosx"], "iconfile": "file_icons/Mac/timestamp_512x512.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
