"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from glob import glob
from setuptools import setup

APP = ['../src/Time Stamper.py']
DATA_FILES = \
    [("../src/classes", glob("../src/classes/*.*")), \
    ("../src/messages", glob("../src/messages/*.*")), \
    ("../src/images", glob("../src/images/*.*"))]
OPTIONS = {"includes": ["tkmacosx"], "iconfile": "../images/file_icons/file_icon_mac.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
