"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from glob import glob
from setuptools import setup

APP = ['Time Stamper.py']
DATA_FILES = \
    [("classes", glob("classes/*.*")), ("messages", glob("messages/*.*")), \
    ("images/program_images", glob("images/program_images/*.*"))]
OPTIONS = {"includes": ["tkmacosx"], "iconfile": "images/file_icons/file_icon_mac.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
